// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvltrjcpecqpplbtzwhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2bHRyamNwZWNxcHBsYnR6d2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MDIyODMsImV4cCI6MjA5NTk3ODI4M30.O0qUrP393DTB44XeOrCtdiW-KEe_W0NjDfUxsfBfRPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});